openshift/agent-installer-utils

tools/agent_tui/app.go, tools/agent_tui/dialogs/panic.go, tools/agent_tui/forms/node0.go, tools/agent_tui/main/main.go, tools/agent_tui/net/nmtui.go
This will allow for minimal code duplication while agent-tui is built in assisted-installer-agent as well.
Signed-off-by: Antoni Segura Puimedon <antoni@redhat.com>
=> AGENT-502: Move App logic out of main

tools/agent_tui/ui/timeout_modal.go
The timeout dialog's border appears to be fixed to gray color. Having a gray colored border causes the dialog to blend into the check screen background color.
The dialog background is now changed to black and the text color changed to white. The timeout dialog is now more distinct.
=> Change timeout dialog background and text color

tools/agent_tui/app.go, tools/agent_tui/checks/engine.go, tools/agent_tui/ui/check_page.go, tools/agent_tui/ui/controller.go, tools/agent_tui/ui/nmtui.go, tools/agent_tui/ui/splashcreen.go, tools/agent_tui/ui/timeout_modal.go, tools/agent_tui/ui/ui.go
The current patch takes care of cancelling the countdown thread when the timeout dialog gets interrupted due a sudden failing check.
In addition to some refactoring to simplify the code, this patch also brings back the timeout dialog to one-off display (it will be shown only the first time)
=> OCPBUGS-7731: Fix cancel user prompt

tools/agent_tui/ui/ui.go
Drop usage of `atomic.Bool` since it required golang 1.19+, and currently this would require another update in the `assisted-installer-agent` CI config that would iimpact also https://github.com/openshift/assisted-installer-agent/pull/482
=> revert to golang 1.18

tools/agent_tui/app.go, tools/agent_tui/app_test.go, tools/agent_tui/checks/engine.go, tools/agent_tui/ui/check_page.go
Also the ci registry does not support ping:
Thus, added a more generic mechanism to support skippings checks, with currently  an hard-coded configuration for the ping check (with some code simplifications)
=> skipping ping check for registry ci

tools/agent_tui/app.go
For example, `registry.build05.ci.openshift.org/...`
=> skipping pings by regexp, to match all possible ci registries

tools/agent_tui/app.go, tools/agent_tui/app_test.go, tools/agent_tui/checks/engine.go, tools/agent_tui/ui/check_page.go, tools/agent_tui/ui/controller.go, tools/agent_tui/ui/ui.go
Now only the pull check can interrupt the timeout dialog if failing.
All the other checks are still being executed in parallel, but their eventual failure will not prevent the agent-tui to automatically close.
Removed also the previous skipping logic.
=> AGENT-565: make the pull check mandatory, the other checks as non blocking

tools/agent_tui/ui/check_page.go, tools/agent_tui/ui/ui.go
Aallow the user to switch the focus between the form buttons and details pane (when visibile). In this way, the user could scroll the details view content by using the up/down arrow keys.
=> Allow the user to scroll the content of the details view

README.md
This patch is required just to trigger the image promotion build, as a first step towards including the agent-installer-utils image into the release payload
=> no-op change to force triggering image promotion build

Makefile, hack/build.sh, pkg/version/version.go, tools/agent_tui/checks/engine.go
Added a Makefile with targets such as `clean`, `lint`, `build`, and `run`. The new variables such as `SOURCE_GIT_COMMIT` and `BUILD_VERSION` are logged in the log file.
=> AGENT-597: Include Doozer build version

tools/agent_tui/app.go, tools/agent_tui/app_test.go, tools/agent_tui/apptester_test.go, tools/agent_tui/checks/engine.go, tools/agent_tui/ui/controller.go, tools/agent_tui/ui/ui.go
Currently when the agent-tui is kicked off during the first boot there's no guarantee that the network will be fully working, thus initially the check could fail and just after a while immediately recover to a green situation, without an explicit user intervention. But the timeout dialog is not activated, and the agent-tui remains active without allowing the boot process to proceed.
This patch fixes the bug by re-activating the timeout dialog if a previously failed check becomes green _and_ if the user didn't interact with the interface. So, as long as the scenario remains stable for 20 seconds, the agent-tui will automatically get closed.
=> OCPBUGS-XXXXX: fix agent-tui stuck on boot 

tools/agent_tui/app.go, tools/agent_tui/app_test.go, tools/agent_tui/apptester_test.go, tools/agent_tui/checks/engine.go, tools/agent_tui/ui/controller.go, tools/agent_tui/ui/ui.go
This is a manual cherry-pick of #26 
(note: this change needs to be vendored in the assisted-installer-agent repo for branch 4.13 to fix [OCPBUGS-15557](https://issues.redhat.com/browse/OCPBUGS-15557))
=> [release-4.13] OCPBUGS-15557: TUI stuck on agent installer network boot setup

go.mod, go.sum, tools/agent_tui/app.go, tools/agent_tui/apptester_test.go, tools/agent_tui/checks/engine.go, tools/agent_tui/main/main.go, tools/agent_tui/ui/check_page.go, tools/agent_tui/ui/controller.go, tools/agent_tui/ui/invalid_ip_address_modal.go, tools/agent_tui/ui/netstate_treeview.go, tools/agent_tui/ui/rendezvous_ip.go, tools/agent_tui/ui/rendezvous_ip_template.go, tools/agent_tui/ui/timeout_modal.go, tools/agent_tui/ui/ui.go, vendor/github.com/joho/godotenv/.gitignore, vendor/github.com/joho/godotenv/LICENCE, vendor/github.com/joho/godotenv/README.md, vendor/github.com/joho/godotenv/godotenv.go, vendor/github.com/joho/godotenv/parser.go, vendor/modules.txt
This change supports a new user scenario whereby the rendezvous IP address may not be written into the agent ISO. In this case, the agent-tui should detect if the NODE_ZERO_IP is specified in /etc/assisted/rendezvous-host.env. If it is unspecified, the tui should display a form to allow the user to enter the rendezvous host IP.
There will be a supporting change in the installer repo to pass the NODE_ZERO_IP from /etc/assisted/rendezvous-host.env to the agent-interactive-console.service which executes agent-tui during boot. If NODE_ZERO_IP is not set in the environment, agent_tui reads /etc/assisted/rendezvous_host.env for the value.
=> AGENT-464: Adds form to agent-tui to enter rendezvous IP address

tools/iso_builder/data/ove/data/systemd/agent-setup-tui.service
quick fix to load the assisted ui image on boot
Required by: https://github.com/openshift/installer/pull/9565
=> AGENT-1087: load agent tui

go.mod, go.sum, tools/agent_tui/app.go, tools/agent_tui/apptester_test.go, tools/agent_tui/checks/engine.go, tools/agent_tui/main/main.go, tools/agent_tui/ui/check_page.go, tools/agent_tui/ui/controller.go, tools/agent_tui/ui/invalid_ip_address_modal.go, tools/agent_tui/ui/netstate_treeview.go, tools/agent_tui/ui/nmtui.go, tools/agent_tui/ui/rendezvous_ip.go, tools/agent_tui/ui/rendezvous_ip_save_success_modal.go, tools/agent_tui/ui/rendezvous_ip_select.go, tools/agent_tui/ui/rendezvous_ip_template.go, tools/agent_tui/ui/timeout_modal.go, tools/agent_tui/ui/ui.go, vendor/github.com/joho/godotenv/.gitignore, vendor/github.com/joho/godotenv/LICENCE, vendor/github.com/joho/godotenv/README.md, vendor/github.com/joho/godotenv/godotenv.go, vendor/github.com/joho/godotenv/parser.go, vendor/modules.txt
Added confirmation screens after the Rendezvous node IP is saved.
Instead of a checkbox to "randomly" choose of the Node's IP as the Rendezvous node IP, a list of all of this node's IP addresses is presented which allows the user to choose the exact one they want.
Added additional descriptions on the form to make the process more understandable.
Depends-on: https://github.com/openshift/agent-installer-utils/pull/38
=> AGENT-464: Refactor UI for Rendezvous node IP entry

tools/iso_builder/data/ove/data/files/usr/local/bin/setup-agent-tui.sh
This also avoids modifying the original /usr/local/bin labels, since it could have an impact in a later stage during the installation
=> AGENT-1118: Ensure the correct selinux labels are applied to agent tui files

tools/iso_builder/hack/build-ove-image.sh
Added support to specify OCP version via --ocp-version or extract version from --release-image-url.
- --release-image-url is mainly for testing/debugging non-released version
- Updated input validation to ensure only one of --ocp-version or --release-image-url is provided.
- Adds channel and cpuArchitecture in appliance-config only if --ocp-version is provided.
- Modified appliance config creation to dynamically include the OCP version based on inputs.
- Improved error handling and default architecture handling.
- Enhanced usage instructions to reflect new input options and examples.
=> AGENT-1137: Support both --ocp-version and --release-image-url

tools/iso_builder/hack/build-ove-image.sh
Appliance allows using an internal registry (see https://github.com/openshift/appliance/pull/349).  Use that (instead of the external one).
=> AGENT-1151: Use internal appliance registry

tools/agent_tui/ui/nmtui.go
The doneFunc() is only called when there is an error executing ShowNMTUI and doesn't need to be called at the end of showNMTUIWithErrorDialog.
=> NO-ISSUE: Remove extra doneFunc() call

tools/iso_builder/Makefile, tools/iso_builder/hack/build-ove-image.sh, tools/iso_builder/hack/cleanup.sh, tools/iso_builder/hack/helper.sh
Unmount appliance mount directory
Add new targets
- `make cleanall` : Cleans default ISOBuilder tmp directory ( /tmp/iso_builder) 
- `make clean-appliance-temp-dir`:  Invokes appliance container to clean appliance temp directory  ( /tmp/iso_builder/<OCP_VERSION>/appliance/temp)
- `make build-ove-iso`: Validates required inputs and creates OVE ISO in default location ( /tmp/iso_builder)
=> NO-ISSUE: ISOBuilder: Add Clean targets.

tools/iso_builder/hack/build-ove-image.sh
Adds `registry.redhat.io/rhel9/support-tools` under `additionalImages` in appliance-config.yaml. This image is required by `oc debug` to launch a debug pod with diagnostic tools for troubleshooting networking, file system, and process issues across nodes and pods.
=> NO-ISSUE: ISOBuilder-Add support-tools image for oc debug

tools/iso_builder/hack/build-ove-image.sh
The recent merge of PR #79 introduced a new `useDefaultSourceNames` field in `appliance-config.yaml,` which the current ISOBuilder appliance image doesn't recognize. 
This causes appliance to fail with the error: `FATAL failed to load asset 'Appliance Config': can't parse appliance-config.yaml. Ensure the config file is configured correctly (error in field 'useDefaultSourceNames'.` 
This commit updates the appliance image SHA to a version that includes support for this new field.
=> NO-ISSUE: Update ISOBuilder appliance image SHA

tools/iso_builder/hack/build-ove-image.sh
This will avoid mirroring multiple versions for the same operator, thus decreasing the OVE ISO size down ~40GB
=> OCPBUGS-56112: configure the channel for each OLM operators

tools/agent_tui/ui/rendezvous_ip_connectivity_fail_modal.go, tools/agent_tui/ui/rendezvous_ip_save_success_modal.go, tools/agent_tui/ui/rendezvous_ip_select.go, tools/agent_tui/ui/rendezvous_modal.go
After quiting nmtui in the install-interactive-disconnected workflow the user should stay in the rendezvous IP selection screens and not shown the release image checks page.
The bug was caused by
https://github.com/openshift/agent-installer-utils/pull/73 which removed the original redirect back to the rendezvous IP pages to fix an issue with the bad_dns e2e test.
=> OCPBUGS-56223: Fix nmtui redirection after quit

tools/agent_tui/ui/nmtui.go
Modal background was set to black making the text (which is also in black) invisible.
When there is an error from nmtui, log it so that is it can be seen there for debugging. Otherwise the error is only visible from the UI.
=> OCPBUGS-56880: Log error from nmtui and change modal background

tools/agent_tui/ui/check_page.go, tools/agent_tui/ui/check_page_test.go
A TAB key press is sometimes ignored if an ESC key is pressed before it.
=> OCPBUGS-56934: Disable ESC key on checks page

tools/agent_tui/ui/check_page.go, tools/agent_tui/ui/rendezvous_ip_connectivity_fail_modal.go, tools/agent_tui/ui/rendezvous_ip_select.go, tools/agent_tui/ui/rendezvous_ip_select_test.go, tools/agent_tui/ui/rendezvous_modal.go
This is a manual cherry pick of https://github.com/openshift/agent-installer-utils/pull/107 [OCPBUGS-59664](https://issues.redhat.com/browse/OCPBUGS-59664).
Entering TAB or LEFT keys after ESC is not reliable and sometimes are not registered through "virsh send-key" leaving the bad_dns test unable to quit agent-tui. Using TAB or LEFT makes exiting out of agent-tui a navigational exercise.
To provide a simplier way to exit agent-tui, the checks page has been updated to recognize the letter 'q' as an alternative means to exit the agent-tui.
=> [release-4.19] OCPBUGS-59666: Enable 'q' and 'c' hotkeys for quit and configure network

tools/iso_builder/README.md, tools/iso_builder/hack/build-ove-image.sh
The agent-tui and nmstate libraries will be extracted during boot by https://github.com/openshift/installer/pull/9828.
They do not need to be inserted into the ISO.
Merge https://github.com/openshift/installer/pull/9828 first.
=> AGENT-1205: Do not include agent-tui and related services

tools/iso_builder/data/ove/data/systemd/agent-setup-tui.service, tools/iso_builder/hack/build-ove-image.sh
The UI image is being renamed to agent-installer-ui.
See https://github.com/openshift/release/pull/67480
We switch the UI to use to the new image name. The old name assisted-install-ui will be retired.
=> AGENT-1254: Switch to agent-installer-ui image

renovate.json
Disable the Konflux Renovate/MintMaker PR updates of go.mod dependencies.  Changes to files in .tekton will still receive PRs, for example for updates to Konflux tasks.
In addition the DependencyDashboard is enabled which will allow Renovate to show recommended dependency updates under Issues, but not actually create the PR.
=> OCPBUGS-61956: Disable Konflux go.mod PR updates

tools/iso_builder/Dockerfile, tools/iso_builder/Makefile
Prevent the output from any earlier steps from being included in the container image created using Dockerfile.
=> OCPBUGS-61946: Include only final ISO in OVE UI container image
